config/routes.rb
Bloccit::Application.routes.draw do
  devise_for :users

  resources :posts

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessible :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  attr_accessible :body, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

# Adding a create method to the posts_controller.rb

def create
  @post = Post.new(params[:post])
  #raise # this will short-circuit the method
  if @post.save
    flash[:notice] = "Post was saved."
    redirect_to @post
  else
    flash[:error] = "There was an error saving the post. Please try again."
    render :new
  end
end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      flash[:notice] = "Post was updated."
      redirect_to @post
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Bloccit", root_path %></li>
      <li><%= link_to "About", about_path %></li>

         <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or 
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>

    </ul>
    
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-error">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    
<%= yield %>
    </div>
</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<div class="row">
  <div class="span6">
    <p>Guidelines for new posts:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
    </ul>
  </div>
  <div class="span6">
    <%= form_for @post, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">
        <%= f.label :title, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :body, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :body, rows: 8 %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.submit "Save", class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<% @posts.each do |post| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to post.title, post %>
      </h4>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="span6">
    <p>Guidelines for new posts:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
    </ul>
  </div>
  <div class="span6">
    <%= form_for @post, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">
        <%= f.label :title, class: 'control-label' %>
        <div class="controls">
          <%= f.text_field :title %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :body, class: 'control-label' %>
        <div class="controls">
          <%= f.text_area :body, rows: 8 %>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <%= f.submit "Save", class: 'btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= link_to "Edit", edit_post_path(@post), class: 'btn btn-mini' %>

<p><%= @post.body %></p>

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<p>Created by: Me</p>

app/views/welcome/index.html.erb
<div class="hero-unit">
  <h1>Bloccit</h1>
  <p>Bloccit is a resource for sharing links with your friends!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary btn-large' %> or 
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary btn-large' %> today!
  </p>
</div>

<div class="row">
  <div class="span4">
    <h2>Amazing Point 1</h2>
    <p>This is some content about how great point 1 is. You should really use Bloccit because of it! No seriously, it really is amazing and great and you should really check it out.</p>
  </div>
  <div class="span4">
    <h2>Amazing Point 2</h2>
    <p>This is some content about how great point 2 is. You should really use Bloccit because of it! No seriously, it really is amazing and great and you should really check it out.</p>
  </div>
  <div class="span4">
    <h2>Amazing Point 3</h2>
    <p>This is some content about how great point 3 is. You should really use Bloccit because of it! No seriously, it really is amazing and great and you should really check it out.</p>
  </div>
</div>